services:
  reverseproxy:
    build: .
    container_name: reverseproxy_th
    restart: unless-stopped
    ports:
      - "888:443"
    volumes:
      - proxy-data:/data
    environment:
      - SECRET_KEY=changez-moi-en-production
      - ADMIN_PASSWORD=root

volumes:
  proxy-data:
