services:
  reversproxy:
    build: .
    container_name: reversproxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "888:443"
    volumes:
      - proxy-data:/data
      - letsencrypt-data:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
      - proxy-logs:/var/log/reverseproxy
    environment:
      - SECRET_KEY=changez-moi-en-production
      - ADMIN_PASSWORD=root

volumes:
  proxy-data:
  letsencrypt-data:
  certbot-webroot:
  proxy-logs:
